# -*- coding: utf-8 -*-
"""Integrator_ and _error_dynamic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18F6huXBaHq-aHfOTnlGN0wjDA-nkcHxK
"""

#Error Analysis of Numerical Differentiation on function

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

dt = 0.1
t = np.linspace(0, 10, 60)
y0 = -2.0
f = np.sin(t)**3 + (np.exp(t)**-6) * 2  #this mimics the price move for very short interval
first_order = 3 * np.sin(t)**2 * np.cos(t) - 12 * np.exp(t)**-7    #first order of price moves

plt.plot(t, f, 'r--')
plt.plot(t, first_order, 'k')
plt.grid(True)
plt.legend(['Function', 'Derivative'])
plt.xlabel('time')
plt.ylabel('function')
plt.title('First order Vs Original Moves')
plt.ylim([-2, 3])
plt.show()



#forward approximation
for_appx = ((np.sin(t+dt)**3 + (np.exp(t+dt)**-6) * 2)  - (np.sin(t)**3 + (np.exp(t)**-6) * 2 )) / dt
#backward_approximation
back_appx = ((np.sin(t)**3 + (np.exp(t)**-6) * 2) - (np.sin(t-dt)**3 + (np.exp(t-dt)**-6) * 2)) /dt
#central_approximation
central_appx = ((np.sin(t+dt)**3 + (np.exp(t+dt)**-6) * 2) - (np.sin(t-dt)**3 + (np.exp(t-dt)**-6) * 2)) / (2*dt)

plt.figure(figsize=(20,6))
plt.subplot(1,2,1)
plt.plot(t, first_order, 'k')
plt.plot(t,for_appx, 'b' )
plt.plot(t, back_appx, 'g')
plt.plot(t, central_appx, 'r')
plt.legend(['Exact Derivative', 'forward Euler','backward Euler','central Euler'])
plt.xlabel('time')
plt.ylabel('function')
plt.title('Error approximation of integrators')
plt.grid(True)
plt.ylim([-2, 3])
plt.show()

plt.figure(figsize=(20,6))
plt.subplot(1,2,1)
plt.plot(t, first_order, 'k')
plt.plot(t,for_appx, 'b' )
plt.plot(t, back_appx, 'g')
plt.plot(t, central_appx, 'r')
plt.legend(['Exact Derivative', 'forward Euler','backward Euler','central Euler'])
plt.xlim([7.5,8])
plt.ylim([-1,2])
plt.show()






